[package]
name = "dbms_proj"
version = "0.1.0"
authors = ["aben20807 <aben20807@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.gtk]
version = "0.6.0"
features = ["v3_16"]

[dependencies.rusqlite]
version = "0.18.0"